import Head from 'next/head'
import HomePage from '../components/homePage'
import { ThemeProvider } from '@mui/material/styles';
import CssBaseline from '@mui/material/CssBaseline';
import darkTheme from '../styles/theme';
import { SeasonContext, useSeasonContextProvider } from '../hooks/useSeasons';

export default function Home() {
  const seasonContextValue = useSeasonContextProvider();

  return (
    <div>
      <Head>
        <title>AniSeason</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ThemeProvider theme={darkTheme}>
        <CssBaseline />
        <SeasonContext.Provider value={seasonContextValue}>
          <HomePage />
        </SeasonContext.Provider>
      </ThemeProvider>
    </div>
  )
}
